include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

variables:
  VM_USER: "warpgate"
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test        # Security scans (SAST/Dependency) run here
  - setup
  - update
  - training
  - deploy

build_app:
  stage: build
  tags:
    - docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - cd backend/app
    - docker build -t "$CI_REGISTRY_IMAGE:app-latest" .
    - docker push "$CI_REGISTRY_IMAGE:app-latest"

train_model:
  stage: training
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - python data/training/ppl-train.py  
  rules:
  - changes:
      - data/**/* - backend/**/* - docker-compose.yml

setup_infra:
  stage: setup
  script:
    - ssh "$CI_SSH_HOST" "sudo mkdir -p /home/$VM_USER/app"
    - rsync -rtvz --delete --exclude 'volumes' . "$CI_SSH_HOST":/home/$VM_USER/app
    - ssh $CI_SSH_HOST "cd /home/$VM_USER/app && sudo docker compose up -d"

deploy_api:
  stage: deploy
  script:
    - ssh $CI_SSH_HOST "sudo docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
    - ssh $CI_SSH_HOST "cd /home/$VM_USER/app && sudo docker compose pull && sudo docker compose up -d"