variables:
  VM_USER: "warpgate"

image: finalgene/openssh

stages:
  - build
  - setup
  - update
  - training
  - deploy

.update_app_image:
  before_script:
    - ssh $CI_SSH_HOST "sudo docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
    - ssh $CI_SSH_HOST "sudo docker pull $CI_REGISTRY_IMAGE:app-latest"

build_app:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:app-latest" -f backend/api/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:app-latest"
  rules:
    - changes:
        - backend/api/**
        - backend/inference/**
        - environment.yml

build_train_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:train-latest" -f backend/inference/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:train-latest"
  rules:
    - changes:
        - data/training/**
        - backend/inference/**
        - environment.yml

setup_infra:
  stage: setup
  script:
    - 'which rsync || ( apk add --update rsync )'
    - ssh "$CI_SSH_HOST" "sudo mkdir -p /home/$VM_USER/app && sudo chown $VM_USER:$VM_USER /home/$VM_USER/app"
    - rsync -rtvz --delete --exclude 'volumes' . "$CI_SSH_HOST":/home/$VM_USER/app
    - ssh $CI_SSH_HOST "cd /home/$VM_USER/app && sudo docker compose down && sudo docker compose up -d"
  rules:
    - when: always

update_data:
  stage: update
  before_script:
    - !reference [.update_app_image, before_script]
  script:
    - ssh $CI_SSH_HOST "sudo docker stop ppl-load_data || true && sudo docker rm ppl-load_data || true"
    - ssh $CI_SSH_HOST "sudo docker run --name ppl-load_data --network mlsdo-lab5_lab5 \
        -v /home/$VM_USER/app/data:/data \
        -e POSTGRES_URL='postgresql://postgres:pw1@postgres-ml:5432/reviews_db' \
        -e MLFLOW_TRACKING_URL='http://mlflow:5000' \
        -e MLFLOW_MODEL_NAME='add_detection_model' \
        $CI_REGISTRY_IMAGE:app-latest python /app/data/preprocessing/ppl-load_data.py"
  rules:
    - changes:
        - data/preprocessing/**            
        - backend/inference/** 

train_model:
  stage: training
  before_script:
    - ssh $CI_SSH_HOST "sudo docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
    - ssh $CI_SSH_HOST "sudo docker pull $CI_REGISTRY_IMAGE:train-latest"
  script:
    - ssh $CI_SSH_HOST "sudo docker stop ppl-train || true && sudo docker rm ppl-train || true"
    - ssh $CI_SSH_HOST "sudo docker run --name ppl-train --network mlsdo-lab5_lab5 \
        -e POSTGRES_URL='postgresql://postgres:pw1@postgres-ml:5432/reviews_db' \
        -e MLFLOW_TRACKING_URL='http://mlflow:5000' \
        -e MLFLOW_MODEL_NAME='add_detection_model' \
        $CI_REGISTRY_IMAGE:train-latest"
  rules:
    - changes:
        - data/training/**
        - backend/inference/**
        - environment.yml

deploy_api:
  stage: deploy
  before_script:
    - !reference [.update_app_image, before_script]
  script:
    - ssh $CI_SSH_HOST "sudo docker stop app-api || true && sudo docker rm app-api || true"
    - ssh $CI_SSH_HOST "sudo docker run -d --name app-api --network mlsdo-lab5_lab5 \
        -e POSTGRES_URL='postgresql://postgres:pw1@postgres-ml:5432/reviews_db' \
        -e REDIS_URL='redis://redis:6379/0' \
        -e MLFLOW_TRACKING_URL='http://mlflow:5000' \
        -e MLFLOW_MODEL_NAME='add_detection_model' \
        -p 8080:8080 $CI_REGISTRY_IMAGE:app-latest"
  rules:
    - changes:
        - backend/api/**
        - backend/inference/**
        - environment.yml
