variables:
  VM_USER: "warpgate"

image: finalgene/openssh

stages:
  - build
  - setup
  - update
  - training
  - deploy

build_app:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - cd app
    - docker build -t "$CI_REGISTRY_IMAGE:app-latest" .
    - docker push "$CI_REGISTRY_IMAGE:app-latest"
  only:
    changes:
      - app/**

setup_infra:
  stage: setup
  # (Note: we can ssh into the VM directly without SSH_PRIVATE_KEY)
  script:
    - 'which rsync || ( apk add --update rsync )'
    - ssh "$CI_SSH_HOST" "sudo mkdir -p /home/$VM_USER/app && sudo chown $VM_USER:$VM_USER /home/$VM_USER/app"
    - rsync -rtvz --delete --exclude 'volumes' . "$CI_SSH_HOST":/home/$VM_USER/app
    - ssh $CI_SSH_HOST "cd /home/$VM_USER/app && sudo docker compose down && sudo docker compose up -d"

.update_app_image:
  before_script:
    - ssh $CI_SSH_HOST "sudo docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
    - ssh $CI_SSH_HOST "sudo docker pull $CI_REGISTRY_IMAGE:app-latest"

update_data:
  stage: update
  before_script:
    - !reference [.update_app_image, before_script]
  script:
    - ssh $CI_SSH_HOST "sudo docker stop ppl-load_data || true && sudo docker rm ppl-load_data || true"
    - ssh $CI_SSH_HOST "sudo docker run --name ppl-load_data --network mlsdo-lab5_lab5 -v /home/$VM_USER/app/data:/data $CI_REGISTRY_IMAGE:app-latest python ppl-load_data.py"

train_model:
  stage: training
  before_script:
    - !reference [.update_app_image, before_script]
  script:
    - ssh $CI_SSH_HOST "sudo docker stop ppl-train || true && sudo docker rm ppl-train || true"
    - ssh $CI_SSH_HOST "sudo docker run --name ppl-train --network mlsdo-lab5_lab5 $CI_REGISTRY_IMAGE:app-latest python ppl-train.py"