name: mlsdo-assignment
services:
  app-api:
    build: 
      context: .  
      dockerfile: ./backend/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=postgresql://postgres:pw1@postgres-ml:5432/reviews_db
      - REDIS_URL=redis://redis:6379/0
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - assignment
    depends_on:
      - postgres-ml
      - redis
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"

  celery-worker:
    build: 
      context: .  
      dockerfile: ./backend/inference/Dockerfile
    command: celery -A tasks worker --loglevel=info
    environment:
      - POSTGRES_URL=postgresql://postgres:pw1@postgres-ml:5432/reviews_db
      - REDIS_URL=redis://redis:6379/0
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - assignment
    depends_on:
      - postgres-ml
      - redis
      - mlflow
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - assignment

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - assignment

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - assignment

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://10.10.0.146:3000
      - GF_SECURITY_ALLOW_EMBEDDING=true            
      - GF_SECURITY_COOKIE_SAMESITE=none            
      - GF_AUTH_ANONYMOUS_ENABLED=false 
    depends_on:
      - prometheus
      - loki
    networks:
      - assignment

  mlflow:
    build: ./mlflow
    ports:
      - "5000:5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio-mlflow:9000
      AWS_ACCESS_KEY_ID: mlflow_access_key
      AWS_SECRET_ACCESS_KEY: mlflow_secret_key
      POSTGRES_URL: postgresql+psycopg2://postgres:pw2@postgres-mlflow:5432/mlflow
    networks:
      - assignment
    depends_on:
      - postgres-mlflow
      - minio-mlflow

  postgres-mlflow:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: pw2
      POSTGRES_DB: mlflow
    ports:
      - "5433:5432" 
    networks:
      - assignment

  minio-mlflow:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: mlflow_access_key
      MINIO_ROOT_PASSWORD: mlflow_secret_key
    networks:
      - assignment

  postgres-ml:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw1
      POSTGRES_DB: reviews_db
    ports:
      - "5432:5432"
    networks:
      - assignment

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: my-secret-pw
    ports:
      - "27017:27017"
    networks:
      - assignment

networks:
  assignment:
    driver: bridge